config/routes.rb
Rails.application.routes.draw do
    resources :friends

  root 'homepage#home'
#   get 'friends', to:'friends#index'
#   get 'friend/:id', to:'friends#show'
#   get 'friend/:id/edit', to:'friends#edit'
#   get 'new', to:'friends#new'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/friend.rb
class Friend < ApplicationRecord
    validates :name, presence:true, length:{maximum:20}
    validates :location, presence:true, length:{maximum:50}
    validates :dob, presence:true
    validates :contact, length:{maximum:10,minimum:10}

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def index
        @friend=Friend.all
    end

    def new
        @friend=Friend.new
    end

    def show
        set_friend
    end

    def edit
        set_friend
    end

    def update
        set_friend
        if get_params[:dob].to_date < Date.today && @friend.update(get_params)
            flash[:notice]=1
            redirect_to @friend
        elsif get_params[:dob].to_date >  Date.today
            flash[:notice]=0
            render 'edit'
        else
            render :edit, status: :unprocessable_entity
        end
    end

    def create
        @friend=Friend.new(get_params)
        if @friend.dob.to_date < Date.today && @friend.save
            flash[:notice]=1
            redirect_to @friend
        elsif @friend.dob.to_date > Date.today
            flash[:notice]=0
            render 'new'
        else
            render :new, status: :unprocessable_entity 
        end
    end

    def destroy
        @friend=Friend.find(params[:id]).destroy
        flash[:notice]=2
        redirect_to friends_path
        
    end

    private

    def get_params
        params.require(:friend).permit(:name, :location, :dob, :contact)
    end

    def set_friend
        @friend=Friend.find(params[:id])
    end


end

app/controllers/homepage_controller.rb
class HomepageController < ApplicationController

    def home 
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/homepage_helper.rb
module HomepageHelper
end

app/views/friends/_form.html.erb
<% if @friend.errors.any? %>
<div class="alert alert-danger" role="alert">
  <h4 class="alert-heading"><%= pluralize(@friend.errors.count, "error") %> prohibited this todo from being saved:!</h4>
    <ul>
        <% @friend.errors.each do |error| %>
          <li class="mb-0"><%= error.full_message %></li>
        <% end %>
      </ul>
    <hr>
  <p class="mb-0">Please check and give proper inputs.</p>
</div>
    
  <% end %>

<%= form_with(model: @friend) do |f| %>


<div class="mb-3 row">
    <%= f.label :name, "Name",{class:"form-label"} %>
    <%= f.text_field :name, {class:"form-control", placeholder:"Enter name...", required: "true"} %>
</div>

<div class="mb-3 row">
    <%= f.label :location, "Location",{class:"form-label"} %>
    <%= f.text_field :location, {class:"form-control", placeholder:"Enter location...", required: "true"} %>
</div>

<div class="mb-3 row">
    <%= f.label :dob, "Date Of Birth",{class:"form-label"} %>
    <%= f.text_field :dob, {class:"form-control", placeholder:"Enter Date of Birth...", required: "true", type:"date"} %>
</div>

<div     class="mb-3 row">
    <%= f.label :contact, "Contact",{class:"form-label"} %>
    <%= f.text_field :contact, {class:"form-control", placeholder:"Enter Contact...",type:"number", required: "true"} %>
</div>
<div class="mb-3 row">
<center>
    <%=f.submit(class:"btn btn-primary mb-3")%>
    </center>
</div>
<% end %>

app/views/friends/edit.html.erb
  <div class="container" style="margin-top:20px;" >
 
  <nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.jpg') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      FRIENDS
    </a>
  </div>
</nav>
<div class="text-success">
  <hr>
</div>
<div class="container" >
<%= render 'form'%>
</div>
<div class="container">
<center>
<%= link_to "GO To Home",friends_path, {class:"btn btn-danger"}%>
</center>
</div>

</div>

app/views/friends/index.html.erb
  <div class="container" style="margin-top:20px;" >
 
  <nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.jpg') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      FRIENDS
    </a>
    <%= link_to "Add New Friend", new_friend_path, {class: "btn btn-outline-primary"} %>

  </div>
</nav>
<div class="text-success">
  <hr>
</div>
<div class="container" >
<table class="table table-hover">
  <thead>
    <tr>
      <th scope="col">Id</th>
      <th scope="col">Name</th>
      <th scope="col">Location</th>
      <th scope="col">Date of Birth</th>
      <th scope="col">Age</th>
      <th scope="col">Contact</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
  <% @friend.each do |fr|%>
    <tr>
      <th scope="row"><%= fr.id %></th>
      <td><%= fr.name %></td>
      <td><%= fr.location %></td>
      <td><%= fr.dob %></td>
      <td><%= (((Date.today - fr.dob.to_date)/365).floor) %></td>
      <td><%= fr.contact %></td>
      <td>
      <div class="btn-group"><%= link_to "Show Friend",friend_path(fr.id), {class:"btn btn-warning"}%><%= link_to "Edit Friend", edit_friend_path(fr), {class:"btn btn-info"}%><%= button_to "Remove Friend",friend_path(fr),data: {turbo_confirm: "Are you sure to delete??"}, method: :delete,  class:"btn btn-danger" %>
        </div>
        </td>
    </tr>
    <% end %>
   
  </tbody>
</table>


</div>

  </div>

app/views/friends/new.html.erb
  <div class="container" style="margin-top:20px;" >
 
  <nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.jpg') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      FRIENDS
    </a>
  </div>
</nav>
<div class="text-success">
  <hr>
</div>
<div class="container" >
<%= render 'form'%>
</div>

</div>

app/views/friends/show.html.erb
 <div class="container" style="margin-top:20px;" >
  <nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.jpg') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      TODO APP
    </a>
  </div>
</nav>
<div class="text-success">
  <hr>
</div>
<div class="container">
<div class="card text-center">
  <div class="card-header">
    <h5 class="card-title"><%= @friend.name.upcase %></h5>
  </div>
  <div class="card-body">
    <p class="card-text"><strong>Location:</strong> <%=@friend.location %></p>
    <p class="card-text"><strong>Date of Birth:</strong> <%= @friend.dob %></p>
    <p class="card-text"><strong>Age:</strong> <%= (((Date.today - @friend.dob.to_date)/365).floor) %></p>
    <p class="card-text"><strong>Contact Number:</strong> <%= @friend.contact %></p>
  </div>
</div>

</div>
<hr>
    <center>
    <div class="btn-group" role="group" aria-label="Basic example">
    <%= link_to "GO To Home",friends_path, {class:"btn btn-danger"}%><%= link_to "Edit Friend", edit_friend_path(@friend), {class:"btn btn-info"}%><%= button_to "Remove Friend",friend_path(@friend),data: {turbo_confirm: "Are you sure to delete??"}, method: :delete,  class:"btn btn-danger" %>
  </div>
  </center>
  </div>
 

app/views/homepage/home.html.erb
 <div class="container" style="margin-top:20px;" >
  <nav class="navbar bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="<%= root_path %>">
     <img src="<%= asset_url('logo.jpg') %>" alt="Logo" width="45" height=40"" class="d-inline-block align-text-top">
      FRIENDS
    </a>
    <%= link_to "Get Started", friends_path, {class: "btn btn-outline-success"} %>

  </div>
</nav>
    <div class="jumbotron" >
    <div id="carouselExampleIndicators" class="carousel slide" data-bs-ride="true">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="<%= asset_url('friend-1.jpg') %>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%= asset_url('friend-2.jpg') %>" class="d-block w-100" alt="...">
    </div>
    <div class="carousel-item">
      <img src="<%= asset_url('friend-3.jpg') %>" class="d-block w-100" alt="...">
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleIndicators" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>
  
</div>
  </div>
 

app/views/layouts/_messages.html.erb
<% flash.each do |key,value|%>
  <%if value==0 %>
  <div class="alert alert-danger" role="alert">
    <center><strong>Check the date of birth ...</strong></center>
    </div>
    <% elsif value==1 %>
    <div class="alert alert-success" role="alert">
    <center><strong>Record saved succesfully..</strong></center>
    </div>
    <%else%>
    <div class="alert alert-success" role="alert">
    <center><strong>Friend removed succesfully..</strong></center>
    </div>
    <%end%>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Veeral</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
       <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

  </head>

  <body>
   <%= render 'layouts/messages'%>
  
    <%= yield %>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>

  </body>
</html>